name: invert_colors
description: A lightweight widget that inverts the colors of its children.
version: 0.0.1
author: Benjamin Swerdlow
homepage: https://github.com/theswerd/InvertColors

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.swerd.invertcolors
        pluginClass: invert_colors
      ios:
        pluginClass: invert_colors
      macos:
        pluginClass: invert_colors
      web:
        pluginClass: invert_colors
        fileName: invert_colors.dart



