name: invert_colors
description: A lightweight widget that inverts the colors of its children.
version: 0.0.4
homepage: https://github.com/theswerd/InvertColors

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



